from Downloaders.kaggleCodeDownloader import getAllKernelsForKaggleMostVotedEntity
from utils.kaggleEnums import KaggleEntityType


getAllKernelsForKaggleMostVotedEntity(KaggleEntityType.COMPETITION,1)