from KaggleDataSetAnalysers.DataSetTypeFileListAnalyser import DataSetTypeFileListAnalyser
from KaggleDataSetAnalysers.DataSetTypeMetaDataAnalyser import DataSetTypeMetaDataAnalyser
from kaggleKernelAnalyser import analyseAllKernels

def fillDatabase():
    analyseAllKernels(dataSetAnalysers=[DataSetTypeMetaDataAnalyser])


fillDatabase()